### PR TITLE
Add funBindsWithFixity

### LINKED ISSUE #78: funBinds doesn't support infix
The fixity of a binding is controlled by the `mc_fixity` parameter of the `HsMatchContext` on a `Match`. `ghc-source-gen` forces this parameter to be `Prefix`, but it would be nice to have the option to control this.

### PR DESCRIPTION
**Pull request by isovector**
Fixes #78

### CODE REVIEW

**Comment by isovector** [comment]
@googlebot I signed it!

**Comment by isovector** [comment]
@blackgnezdo @judah hey lovely maintainers! Any chance of getting this merged?

**Review by judah — APPROVED** [review]

**Comment by judah** [comment]
Thank you for the contribution!

**Comment by isovector** [comment]
Thanks for the merge!

**Pull request merged**
