### PR TITLE
Add standaloneDeriving

### PR DESCRIPTION
**Pull request by ersran9**

### CODE REVIEW

**Comment by blackgnezdo** [comment]
@judah are we [pre-broken](
https://app.circleci.com/pipelines/github/google/ghc-source-gen/186/workflows/ccb8df70-9fbc-4eb9-b379-d97268858336/jobs/839)?
```
ghc-source-gen      > [24 of 27] Compiling GHC.SourceGen.Decl
ghc-source-gen      > 
ghc-source-gen      > /home/circleci/project/src/GHC/SourceGen/Decl.hs:59:1: error: [-Wunused-imports, -Werror=unused-imports]
ghc-source-gen      >     The import of ‘HsWildCardBndrs’
ghc-source-gen      >     from module ‘GHC.Hs.Types’ is redundant
ghc-source-gen      >    |
ghc-source-gen      > 59 | import GHC.Hs.Types
ghc-source-gen      >    | ^^^^^^^^^^^^^^^^^^^...
ghc-source-gen      > 
```

**Comment by ersran9** [comment]
There is a warning that I missed out, let me push again with that removed.

**Comment by ersran9** [comment]
Whew - that's what I get for trying to use cabal on a stack project. Also, I just noticed that [build-ghc-8.10](https://app.circleci.com/pipelines/github/google/ghc-source-gen/186/workflows/ccb8df70-9fbc-4eb9-b379-d97268858336/jobs/838) on CI actually runs the command `stack test --no-terminal --resolver=lts-15.13` - which uses [ghc-8.8.3](https://www.stackage.org/lts-15.13).

**Review by blackgnezdo — APPROVED** [review]
Very nice, thank you for adding the tests!

**Comment by blackgnezdo** [comment]
@judah, this looks like an improvement to me, so I'll merge it and we can fix up later if need be.

**Pull request merged**
