### PR TITLE
Support GHC 9.4

### LINKED ISSUE #99: GHC 9.4 compatibility
If I override the bounds, I currently get this error, building with GHC 9.4:

```
Building library for ghc-source-gen-0.4.3.0..
[ 1 of 18] Compiling GHC.SourceGen.Pretty ( src/GHC/SourceGen/Pretty.hs, dist/build/GHC/SourceGen/Pretty.o, dist/build/GHC/SourceGen/Pretty.dyn_o )
[ 2 of 18] Compiling GHC.SourceGen.Syntax.Internal ( src/GHC/SourceGen/Syntax/Internal.hs, dist/build/GHC/SourceGen/Syntax/Internal.o, dist/build/GHC/SourceGen/Syntax/Internal.dyn_o )
[ 3 of 18] Compiling GHC.SourceGen.Name.Internal ( src/GHC/SourceGen/Name/Internal.hs, dist/build/GHC/SourceGen/Name/Internal.o, dist/build/GHC/SourceGen/Name/Internal.dyn_o )
[ 4 of 18] Compiling GHC.SourceGen.Name ( src/GHC/SourceGen/Name.hs, dist/build/GHC/SourceGen/Name.o, dist/build/GHC/SourceGen/Name.dyn_o )
[ 5 of 18] Compiling GHC.SourceGen.Lit.Internal ( src/GHC/SourceGen/Lit/Internal.hs, dist/build/GHC/SourceGen/Lit/Internal.o, dist/build/GHC/SourceGen/Lit/Internal.dyn_o )
[ 6 of 18] Compiling GHC.SourceGen.Pat.Internal ( src/GHC/SourceGen/Pat/Internal.hs, dist/build/GHC/SourceGen/Pat/Internal.o, dist/build/GHC/SourceGen/Pat/Internal.dyn_o )

src/GHC/SourceGen/Pat/Internal.hs:54:27: error:
    • Couldn't match type: Language.Haskell.Syntax.Extension.XRec
                             p0 (Pat p0)
                           -> Language.Haskell.Syntax.Extension.XRec
                                p0 (Language.Haskell.Syntax.Extension.HsToken ")")
                           -> Pat p0
                     with: Pat GHC.Hs.Extension.GhcPs
      Expected: GHC.Parser.Annotation.EpAnn ann0
                -> Language.Haskell.Syntax.Extension.XRec
                     p0 (Language.Haskell.Syntax.Extension.HsToken "(")
                -> Pat'
        Actual: Language.Haskell.Syntax.Extension.XParPat p0
                -> Language.Haskell.Syntax.Extension.LHsToken "(" p0
                -> Language.Haskell.Syntax.Pat.LPat p0
                -> Language.Haskell.Syntax.Extension.LHsToken ")" p0
                -> Pat p0
    • Probable cause: ‘ParPat’ is applied to too few arguments
      In the first argument of ‘withEpAnnNotUsed’, namely ‘ParPat’
      In the first argument of ‘(.)’, namely ‘withEpAnnNotUsed ParPat’
      In the expression: withEpAnnNotUsed ParPat . builtPat
   |
54 | parPat = withEpAnnNotUsed ParPat . builtPat
   |                           ^^^^^^
```

### PR DESCRIPTION
**Pull request by ocharles**
Fixes #99.

### CODE REVIEW

**Comment by blackgnezdo** [comment]
Thanks @ocharles for the patch! Would you mind signing the CLA?

**Comment by ocharles** [comment]
@blackgnezdo Done

**Comment by stepcut** [comment]
This patch is great, but it would be even better if it bumped all references to `ghc < 9.3` in the `ghc-source-gen.cabal` and `package.yaml` file.

thanks.

**Comment by ocharles** [comment]
@stepcut I believe that's now done.

**Comment by stepcut** [comment]
> @stepcut I believe that's now done.

Closer! When nix builds this package it seems to look at the `package.yaml` and regenerate the `.cabal` from that -- so it would be sweet if you updated `package.yaml` as well. I don't really understand what is going on here. All I know is that updating `9.3` to `9.5` in both files fixed it for me.

**Comment by blackgnezdo** [comment]
Sadly it looks like our CI is broken. We can merge this, but until we have a working CI covering 9.4, I wouldn't feel comfortable making a release to hackage.

**Comment by blackgnezdo** [comment]
@jinwoo what do you think?

**Comment by jinwoo** [comment]
Thanks. Yeah, unfortunately we don't seem to have CI set up in this repo. It'd be great if someone can verify this PR with 9.4. Maybe you already did, @ocharles ?

**Comment by ocharles** [comment]
It certainly builds with GHC 9.4, but I don't think I've actually ran the code that uses this dependency (I'm not responsible for that project). I'll try and see if I can do that and I'll report back.

**Comment by mbj** [comment]
I'm using `ghc-source-gen` with https://github.com/mbj/stratosphere and would be happy to try generating on 9.4. In theory it should produce the same concrete syntax. This would validate this patch.

Can get to it later the week unless someone beats me to it.

**Comment by ocharles** [comment]
@mbj Did you get a chance to try this? I unfortunately am not familiar with the bit of code at work that uses `ghc-source-gen`, and the original author has now left. It might be easier if you try testing this, but I know it does at least build!

**Comment by mbj** [comment]
Sorry did not get around to do this, will try this weekend "OSS maintainer promise" ;) (I hope you get the sarcasm).

**Comment by 4eUeP** [comment]
Any updates for this PR? I've tested this with proto-lens <https://github.com/4eUeP/proto-lens/commit/073b75d991531bfbd59beb2d612367699f699d82>, and it seems nothing broke. 

Also, would you mind updating the small tool under the `ghc-show-ast` directory to ghc9.4? @ocharles

**Comment by mbj** [comment]
@ysangkok Happy OSS maintainer promise! I also get some pressure to release new stratosphere so this may fit.

**Comment by avdv** [comment]
Hey! We are also [using this](https://github.com/tweag/rules_haskell/blob/7c8be73dc5c0f64cd3bdd6169652b52a9816470f/stackage_snapshot_9.4.6.yaml#L23-L25) with proto-lens-protoc and test on CI. We have tested with GHC 9.4.5 and 9.4.6 and no issues have turned up so far.

**Comment by jinwoo** [comment]
@avdv Thanks for the update. Now that you confirmed this change works fine in your CI, I'll merge this now. Thanks!

**Comment by mbj** [comment]
@jinwoo Chances you can push a release to hackage?

**Comment by mbj** [comment]
OT: This PR also works also for my straosphere project, sorry I could not test it earlier: https://github.com/mbj/stratosphere/pull/225

**Pull request merged**
