### PR TITLE
Add support for GHC 9.2

### PR DESCRIPTION
**Pull request by brandon-leapyear**

### CODE REVIEW

**Comment by blackgnezdo** [comment]
I'm confused why CI is not working. Any ideas?

**Comment by brandon-leapyear** [comment]
Still working on it :)

**Comment by brandon-leapyear** [comment]
Oh and CI didnt run because I prefixed the commit with "[ci skip]"

**Comment by brandon-leapyear** [comment]
Ok made a bit of headway. If anyone else has time, feel free to take this over. This is a pretty tough codebase to update :)

**Comment by brandon-leapyear** [comment]
Got it to compile locally! Not sure if everything is the "correct" way to fix it, but I got it working. Feel free to suggest changes

**Comment by blackgnezdo** [comment]
I notice we lost ghc-9.0 from our CI, do you believe it's not useful? Considering we still have 9.0-specific `ifdef`'s, it appears to make sense to check that version too.

**Comment by brandon-leapyear** [comment]
ah you're right. just re-added it

**Review by blackgnezdo — APPROVED** [review]

**Comment by blackgnezdo** [comment]
@jinwoo maybe you have write access to merge this? I don't...

**Comment by jinwoo** [comment]
Thanks!

**Pull request merged**
