### PR TITLE
Repair unintentionally broken GHC 8.10.7 support

### PR DESCRIPTION
**Pull request by blackgnezdo**
I needed to change a bunch more files, so might as well include the fix of #109 here.

### CODE REVIEW

**Comment by blackgnezdo** [comment]
@jinwoo if you can figure out in the settings why it still wants to run circleci, that should help us get an actually working CI using github actions.

**Comment by jinwoo** [comment]
> @jinwoo if you can figure out in the settings why it still wants to run circleci, that should help us get an actually working CI using github actions.

I deleted the circleci webhook. I'm not sure that's enough. I still see circleci as "required" above.

**Comment by jinwoo** [comment]
I'll force merge this for now.

**Comment by blackgnezdo** [comment]
Thanks @jinwoo. I published the package so #109 is not fixed.

**Pull request merged**
