### PR TITLE
Release for ghc 9.8

### PR DESCRIPTION
**Pull request by blackgnezdo**

### CODE REVIEW

**Comment by blackgnezdo** [comment]
@agrue could you merge this?

**Comment by agrue** [comment]
Sure. The check "ci/circleci: build-success" hasn't completed yet. I don't know how this CI stuff works... do we still expect this to complete at some point or should I bypass it?

**Comment by agrue** [comment]
The check still said "Waiting for status to be reported" after a day, so I just merged it.

**Comment by blackgnezdo** [comment]
Thanks! If you can figure out how to disable this circleci that we no longer use - please do so.

**Pull request merged**
